### ISSUE TITLE
In_Player Animation

### ISSUE THREAD

**Issue by Yashvanth343** [jhelumcorp/gyawun#105]
### Feature description

![IMG_20231002_113355](https://github.com/jhelumcorp/gyawun/assets/72242474/a116acf3-1ca1-42e1-a55d-386b7ef5ce33)

**Comment by Yashvanth343** [comment]
On clicking that the player could expand
![Screenshot_2023-10-02-11-35-38-87_be392476dfed2bfea5f62a4ea0a54a31](https://github.com/jhelumcorp/gyawun/assets/72242474/ca1f7faf-84d4-4652-af77-d78f79743c92)

**Comment by sheikhhaziq** [comment]
Didn't understand what you meant
