### ISSUE TITLE
Player animation bug

### ISSUE THREAD

**Issue by Yashvanth343** [jhelumcorp/gyawun#109]
### Steps to reproduce the bug

1. Play a song
2. Open the 'next up' menu
3. Move another song to the top of the list
4. Now delete the another song

### Expected behavior

The player moves

### Actual behavior

The player stucks

### Screenshots/Screen recordings

https://t.me/jhelumcorp/285/431

### Gyawun version

1.0.0

### Android version

Android 13

**Comment by sheikhhaziq** [comment]
Confirm if this bug still exists.
