### ISSUE TITLE
Support for Video Songs

### ISSUE THREAD

**Issue by ankitshekhawat21** [jhelumcorp/gyawun#112]
### Feature description

You can implement it like in Simpmusic app , you can check that app out , that app is having issues with crashing , i thought this app can also have it. Please reply with atleast a yes or no.
![Screenshot_2023-12-02-14-39-38-285_com maxrave simpmusic](https://github.com/jhelumcorp/gyawun/assets/152591602/de3666d9-f71c-4e84-be0e-55e0c13c894a)

**Comment by sheikhhaziq** [comment]
Option to enable video playback will be added soon
