### ISSUE TITLE
Constantly crashes as playback starts

### ISSUE THREAD

**Issue by idontveapc** [jhelumcorp/gyawun#119]
### Steps to reproduce the bug

- play any song
  - as it plays the app crashes and playback continues for few secs

### Expected behavior

Crash should happen

### Actual behavior

Dint crashed instead 

### Screenshots/Screen recordings

... I'll have record and compress then upload (due to github restricting files' size). I'd if this issue isn't reproducible.

### Logs

where?

### Gyawun version

1.0.1

### Android version

android 11 go (32bit)

### Additional information

*response*

**Comment by sheikhhaziq** [comment]
Issue was marked completed as changes have been made and applied to beta version which you can download.
