### ISSUE TITLE
Fold Z 4  app has all on screen controls, when un-folded to larger screen,  all of the music controls dissappear. (resolution adjustment)

### ISSUE THREAD

**Issue by JasonWilder117** [jhelumcorp/gyawun#121]
### Steps to reproduce the bug

opened the app and ran it on front small screen, all works and shows UI controls as designed.  When fold 4 is opened the music and app taskbar controls are removed.  I believe this to just be a resolution.  Screenshots are attached from my fold 4.

![largeunfoldedacreen](https://github.com/jhelumcorp/gyawun/assets/132273347/0d4c8693-caff-44d1-a4b5-9fced5a244df)
![smallfrontscreenOK](https://github.com/jhelumcorp/gyawun/assets/132273347/0e968273-dd27-4849-8fca-9781d136e288)

### Expected behavior

small screen should have all the controls on the larger screen

### Actual behavior

opened the app and ran it on front small screen, all works and shows UI controls as designed.  When fold 4 is opened the music and app taskbar controls are removed.  I believe this to just be a resolution.  Screenshots are attached from my fold 4.

### Screenshots/Screen recordings

![largeunfoldedacreen](https://github.com/jhelumcorp/gyawun/assets/132273347/816fd764-149f-49ff-bd45-9b81721f1d29)
![smallfrontscreenOK](https://github.com/jhelumcorp/gyawun/assets/132273347/2c3c2b11-ac99-4b1e-ab31-7ecea2dab927)

### Gyawun version

latest V1.01

### Android version

Android 13

### Additional information

Love the app, this is the only fix i see needed.   great work!

**Comment by sheikhhaziq** [comment]
Can you confirm if the bug still exists. Use beta latest version and reopen this issue to let me know or contact me via telegram group
