### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by mkr-infinity** [jhelumcorp/gyawun#122]
### Feature description

Can u please add yt music login or aync with music app .
Or Import and export playlist.
Thanks for such beautiful app.

**Comment by sheikhhaziq** [comment]
Optional login with youtube. And importing playlists from youtube will be added but not in next update, but the one after that.

**Comment by gmankab** [comment]
yes it would be nice

**Comment by sheikhhaziq** [comment]
Support for youtube account has been added in  [this commit](https://github.com/jhelumcorp/gyawun/commit/e06ed42301d346be3f866f8a30f05c65ce9a9353). You can now fetch YTMusic playlists, history in library section. More features will be added soon. Beta update with this functionality will be released within a day.

**Comment by gmankab** [comment]
that is really good news, waiting for next beta release

**Comment by mkr-infinity** [comment]
> Support for youtube account has been added in [this commit](https://github.com/jhelumcorp/gyawun/commit/e06ed42301d346be3f866f8a30f05c65ce9a9353). You can now fetch YTMusic playlists, history in library section. More features will be added soon. Beta update with this functionality will be released within a day.

Love it bro 😀 thanks for beautiful app.
Keep it up.
