### ISSUE TITLE
Add lyrics translation to gyawun music app

### ISSUE THREAD

**Issue by Anonymous18-101** [jhelumcorp/gyawun#124]
I have downloaded the latest update of gyawun beta v2 and I have seen lyrics and account options which are quite useful please add the lyrics translation to English. Like for example Japanese to English lyrics translation so the person who is listening can actually know what they're singing and it will make your application 10 times better than Spotify or any application out there ...

**Comment by sheikhhaziq** [comment]
I will be looking for the api that provides translations for lyrics. when I do so, I will add it to app.
