### ISSUE TITLE
Gyawun 2.0.0-beta-v3 text is mushed together with no space previous version looks more better actually the ui and style 

### ISSUE THREAD

**Issue by Anonymous18-101** [jhelumcorp/gyawun#125]
Gyawun 2.0.0-beta-v3 text is mushed together with no space previous version looks more better actually the ui and style and please add account so when we delete and install new apk of gyawun we can just have the playlist we created without losing ![Screenshot_2024-07-10-11-55-40-987_com.jhelum.gyawun.beta.jpg](ht![Screenshot_2024-07-10-11-55-44-896_com.jhelum.gyawun.beta.jpg](https://github.com/jhelumcorp/gyawun/assets/174444607/85c4640a-5a29-4d9f-8844-f950aa115a37)

tps://github.com/jhelumcorp/gyawun/assets/174444607/1f4bf4ad-62f8-4b93-ac0a-484ba11c47ba)

As you see I tagged the picture where the country is like mashed together with no gap it looks kind of goofy

**Comment by sheikhhaziq** [comment]
Problem seems to be with drop-down menu.

**Comment by sheikhhaziq** [comment]
What about these item tiles?
![Screenshot_2024-07-10-12-43-45-108_com jhelum gyawun beta-edit](https://github.com/jhelumcorp/gyawun/assets/41983383/b9a736a4-2aae-474a-9066-9faff1329113)

**Comment by Anonymous18-101** [comment]
> Problem seems to be with drop-down menu.

![Screenshot_2024-07-10-16-59-37-803_com.jhelum.gyawun.beta.jpg](https://github.com/jhelumcorp/gyawun/assets/174444607/11858f03-252c-465a-98d4-a644a9898438)
