### ISSUE TITLE
BUG REPORT OF GYAWUN 2.0.0-BETA-3

### ISSUE THREAD

**Issue by Anonymous18-101** [jhelumcorp/gyawun#126]
I don't know how but I forgot about this issue in the application i discovered this like before 5 days a week perhaps here is the video I don't know how to explain about this bug or crash https://github.com/jhelumcorp/gyawun/assets/174444607/065a9598-c229-41f0-9700-ffcab523342b

**Comment by sheikhhaziq** [comment]
Thanks for Reporting this issue. I'll look into it.
