### ISSUE TITLE
You solved the search bug but now this happened 

### ISSUE THREAD

**Issue by Anonymous18-101** [jhelumcorp/gyawun#127]
![Screenshot_2024-07-17-22-13-49-514_com.jhelum.gyawun.beta.jpg](https://github.com/user-attachments/assets/724afbc1-154a-4d5e-89fd-b7e6349ea1c9)

Btw great job on things i issued to you 
Fix this...

**Comment by sheikhhaziq** [comment]
Your reviews have been helpful. I have made changes to the app. You can download the updated app [here](https://drive.google.com/file/d/1MeRLaynGnrN1KpHya4v-Ggal9UTGkFfG/view?usp=drivesdk). Feel free to test it and report any issues if you find.

**Comment by Anonymous18-101** [comment]
> Your reviews have been helpful. I have made changes to the app. You can download the updated app [here](https://drive.google.com/file/d/1MeRLaynGnrN1KpHya4v-Ggal9UTGkFfG/view?usp=drivesdk). Feel free to test it and report any issues if you find.

Don't worry your consistency is always superior ❤️ may god bless you and you may become great app creator...
