### ISSUE TITLE
Playlist can't load more than 100 tracks

### ISSUE THREAD

**Issue by Vad1mCSO2** [jhelumcorp/gyawun#142]
https://music.youtube.com/playlist?list=PLP0GS_ZCS9IG1B6O2LbyMiY5TuC1K_NZC This issue got 100 out of 301 tracks

**Comment by sheikhhaziq** [comment]
I'll look into it.

**Comment by sheikhhaziq** [comment]
problem has been fixed in latest commit  and will be available in new release.
