### ISSUE TITLE
Request for linux support

### ISSUE THREAD

**Issue by emanuelebiondi** [jhelumcorp/gyawun#162]
I love your app and its functionality on Windows! I wanted to ask if you would consider adding support for Linux. As a Linux user, I would greatly appreciate being able to use your application on my distribution.

**Comment by sheikhhaziq** [comment]
right now,  the fluent_ui library is having some problems on Linux. I'll still try to find a way.

**Comment by sheikhhaziq** [comment]
closing as it is duplicate of #45
