### ISSUE TITLE
Download path for the music

### ISSUE THREAD

**Issue by neonbaba** [jhelumcorp/gyawun#163]
First of all the app works great and there is a small suggestion that may be great to add, which is setting the download path for music such as sd card support will be beneficial and also some additional settings for downloads like download quality as such.

**Comment by sheikhhaziq** [comment]
I'll look into it.

**Comment by androidghosh** [comment]
Direct download to sd card would be great

**Comment by sheikhhaziq** [comment]
I have added an option to select custom App Folder in new release
