### ISSUE TITLE
I have another bug 🐛

### ISSUE THREAD

**Issue by Anonymous18-101** [jhelumcorp/gyawun#169]
When i downloaded my custom playlist manually one by one the file format is now "mp4" instead of "mp3" or "m4a" my phone gallery is filled with the songs if i changed the file format "mp4" to "mp3" now that my file is missing download again and now some files are in web.m format some are in "mp4" not mp3 or "m4a" like old gyawun update used to be 
![Screenshot_2024-10-30-20-14-31-444_com.jhelum.gyawun.jpg](https://github.com/user-attachments/assets/3a199dd9-2d4d-40d9-b2d0-9c3989ea8dfa)
↑ As you can see in this screenshot "slay" file is now missing due to change of file format in gyawun even if i manually pasted the renamed file in gyawun file directories it doesn't work.
https://github.com/user-attachments/assets/ce3cac59-0b0d-48b2-a02a-ef7b1c84ac3e
As you can see in this video is the bug which file format change from m4a to webm

**Comment by sheikhhaziq** [comment]
It'll be fixed within a day.

**Comment by Anonymous18-101** [comment]
> It'll be fixed within a day.

Happy diwali

**Comment by Anonymous18-101** [comment]
> It'll be fixed within a day.

Happy diwali

**Comment by Anonymous18-101** [comment]
> It'll be fixed within a day.

Happy diwali

**Comment by Anonymous18-101** [comment]
> It'll be fixed within a day.

Happy diwali

**Comment by Anonymous18-101** [comment]
> It'll be fixed within a day.

It's been a day ಠ⁠_⁠ಠ

**Comment by sheikhhaziq** [comment]
It has been fixed in v2.0.7
