### ISSUE TITLE
Problem about the file name m4a somewhat replaced with(web.....)

### ISSUE THREAD

**Issue by Jugram69** [jhelumcorp/gyawun#173]
The 2.06 new version was so disappointing the (m4a) that comes with the image album was nowhere to be found and replaced with .(web em,) something like that I don't know if the new update is has new changes lastly when I try to download a music it goes to my gallery with the name(web.**)so I think it's a bug or changes according to the new version.I like the old version but it was very buggy but the nice thing is the files were written as m4a and have album images pls fix it

**Comment by Jugram69** [comment]
Don't know if this is a bug but when I updated to the newer version this (web)thing is applied to the music file when I download a music

**Comment by sheikhhaziq** [comment]
It has been fixed in v2.0.7

**Comment by sheikhhaziq** [comment]
Album images will be fixed in new version.
