### ISSUE TITLE
No longer shows artist name or logo

### ISSUE THREAD

**Issue by BlvckD3ath** [jhelumcorp/gyawun#175]
No artist name, album, or album logo. Shows as unknown artist as of last update after you download music.

**Comment by sheikhhaziq** [comment]
I have noticed this problem. I am currently working it.

**Comment by sheikhhaziq** [comment]
> I have been investigating this issue for some days now. I am currently stuck, and I will drop my findings here, just in case it helps someone. ;)
> 
> * the issue with metadata not being embedded to downloaded files is the following error being thrown at `file_storage.dart L#131`. (`await AudioTags.write(file.path, tag);`)
> 
> ```
> AudioTagsError.openFile(message: No format could be determined from the provided file)
> ```
> 
> * this only happens when download quality is set to "high" for some reason. I suspected this to be an issue with the await keyword not working as expected, tried [this](https://stackoverflow.com/a/53401995/9652621) solution for it, but that didn't work either.
> 
> PS: I might be completely dumb here! I am not even a flutter developer (haven't written a single line of dart code prior). this is a highly desirable feature for me personally, hence ventured to do this stunt!

You are right, youtube returns two types of data i.e. webm and mp4. Audiotags package only supports mp4 not webm. In previous version, i tried to use webm and that's what caused the problem. I have reverted it back onto mp4 and it works fine again.
