### ISSUE TITLE
Song Delete Option In Playlist 

### ISSUE THREAD

**Issue by karanempire2402** [jhelumcorp/gyawun#181]
Hey Team, I Hope You All Are Doing Good, There Is A Feature Request From My Side, Like Currently There Is No Option Available In Self Created Playlists To Delete Song From It. It Will Be Very Helpful If You Guys Can Add That Feature In Future Updates.
Thanks A Lot.

**Comment by sheikhhaziq** [comment]
Swipe left on song to delete it.
